export const ButtonYrnStyle = {
  '.rce-button': {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    borderRadius: '5px',
    cursor: 'pointer',
    padding: '8px',
    textAlign: 'center',
    boxSizing: 'border-box',
    background: '#3979aa',
    color: 'white',
    transition: 'all 0.15s ease',
    userSelect: 'none',
    border: ['none', 'none'],
    outline: 'none',
    position: 'relative',
  },
  '.rce-button-icon--container': { display: 'flex', alignItems: 'center' },
  '.rce-button:hover': { opacity: 0.8 },
  '.rce-button:active': { opacity: 0.6 },
  '.rce-button.outline': {
    background: 'rgba(0, 0, 0, 0) !important',
    border: '1px solid #3979aa',
    color: '#3979aa',
  },
  '.rce-button.outline:hover': { opacity: 0.6 },
  '.rce-button.outline:active': { opacity: 0.3 },
  '.rce-button.transparent': { background: 'rgba(0, 0, 0, 0) !important' },
  '.rce-button.transparent:hover': { opacity: 0.6 },
  '.rce-button.transparent:active': { opacity: 0.3 },
  '.rce-button-icon': {
    position: 'relative',
    fontSize: '18px',
    display: 'flex',
    padding: '0 3px',
  },
  '.rce-button-badge': {
    borderRadius: '4px',
    padding: '4px',
    background: '#f64b34',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: '-7px',
    top: '-7px',
    fontSize: '10px',
  },
  '.rce-button.circle': {
    minWidth: '35px',
    minHeight: '35px',
    border: '1px solid #3979aa',
    borderRadius: '100%',
  },
}
