import { ContentType, LinkType } from '../@types/LinkType'

export const links01R: LinkType[] = [
  {
    idUser: '1',
    iconLibrary: 'Ionicons',
    iconName: 'ios-calendar-outline',
    contentType: ContentType['linkHref'],
    contentSrc: 'https://calendly.com/romanch',
    content: 'Feel free to setup a phone call',
    label: 'Link',
    isActive: true,
  },
  {
    idUser: '1',
    iconLibrary: 'Ionicons',
    iconName: 'ios-logo-linkedin',
    contentType: ContentType['linkHref'],
    contentSrc: 'https://www.linkedin.com/in/romanches',
    content: 'Profile in Linkedin.com',
    label: 'Link',
    isActive: true,
  },
  {
    idUser: '1',
    iconLibrary: 'Ionicons',
    iconName: 'ios-logo-stackoverflow',
    contentType: ContentType['linkHref'],
    contentSrc: 'https://stackoverflow.com/users/4791116/roman',
    content: 'Profile in Stackoverflow',
    label: 'Link',
    isActive: true,
  },
  {
    idUser: '1',
    iconLibrary: 'Ionicons',
    iconName: 'ios-logo-github',
    contentType: ContentType['linkHref'],
    contentSrc: 'https://github.com/ybeaz',
    content: 'Profile in Github',
    label: 'Link',
    isActive: true,
  },
  {
    idUser: '1',
    iconLibrary: undefined,
    iconName: undefined,
    contentType: ContentType['imageSrc'],
    contentSrc: 'https://r1.userto.com/img/romanChesQrCodeQuietZone00.png',
    content: '',
    label: 'QR code with contacts',
    isActive: true,
  },
]
