import { SectionMappingType } from '../@types/SectionMappingType'

import { SectionType } from '../@types/SectionType'

export const sectionsMapping: SectionMappingType[] = [
  {
    idProfile: '1',
    profileName: '@rome',
    contentType: SectionType['ProjectType'],
    title: 'Projects And Work Examples',
    pathname: 'projects',
    iconLibrary: 'Ionicons',
    iconName: 'briefcase-outline',
    iconTitleText: 'Portfolio',
    childName: 'Portfolio',
  },
  {
    idProfile: '1',
    profileName: '@rome',
    contentType: SectionType['CompetencyTagType'],
    title: 'Technologies',
    pathname: 'technologies',
    iconLibrary: 'Ionicons',
    iconName: 'cog-outline',
    iconTitleText: 'Technologies',
    childName: 'CompetencyTags',
  },
  {
    idProfile: '2',
    profileName: '@smid',
    contentType: SectionType['ProjectType'],
    title: 'Work Examples',
    pathname: 'work-examples',
    iconLibrary: 'Ionicons',
    iconName: 'briefcase-outline',
    iconTitleText: 'Works',
    childName: 'Portfolio',
  },
  {
    idProfile: '2',
    profileName: '@smid',
    contentType: SectionType['CompetencyTagType'],
    title: 'Competency Tags',
    pathname: 'skills',
    iconLibrary: 'Ionicons',
    iconName: 'cog-outline',
    iconTitleText: 'Skills',
    childName: 'CompetencyTags',
  },
  {
    idProfile: '2',
    profileName: '@smid',
    contentType: SectionType['ProfileType'],
    title: '',
    pathname: 'profile',
    iconLibrary: 'Ionicons',
    iconName: 'person-outline',
    iconTitleText: 'Profile',
    childName: 'Profile',
  },
  {
    idProfile: '16',
    profileName: '@yourails',
    contentType: SectionType['CompetencyTagType'],
    title: 'Technologies',
    pathname: 'technologies',
    iconLibrary: 'Ionicons',
    iconName: 'cog-outline',
    iconTitleText: 'Technologies',
    childName: 'CompetencyTags',
  },
  {
    idProfile: '16',
    profileName: '@yourails',
    contentType: SectionType['CompetencyTagType'],
    title: '',
    pathname: 'profile',
    iconLibrary: 'Ionicons',
    iconName: 'person-outline',
    iconTitleText: 'Profile',
    childName: 'Profile',
  },
  {
    idProfile: '16',
    profileName: '@yourails',
    contentType: SectionType['CompetencyTagType'],
    title: '',
    pathname: 'about',
    iconLibrary: 'Ionicons',
    iconName: 'book-outline',
    iconTitleText: 'About us',
    childName: 'AboutUs',
  },
  {
    idProfile: '1',
    profileName: '@rome',
    contentType: SectionType['ProfileType'],
    title: '',
    pathname: 'profile',
    iconLibrary: 'Ionicons',
    iconName: 'person-outline',
    iconTitleText: 'Profile',
    childName: 'Profile',
  },
]
